apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

images:
- name: ${owlcms-docker}/owlcms
  newName: owlcms
  newTag: ${project.version}
- name: ${owlcms-docker}/publicresults
  newName: publicresults
  newTag: ${project.version}

resources:
- ingress.yaml
- services.yaml
- secrets.yaml

