
image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 8082
    onOpen: open-browser

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - name: maven
    # change working directory as per configured in `checkoutLocation`
    # which is configured above as `/workspaces/backend`
    #before: |
    #  echo before
    #init: |
    #  echo init
    #command: |
    init: |
      echo Copying settings
      cp -f /workspace/owlcms4/.gitpod/settings.xml /home/gitpod/.m2/settings.xml
      echo creating shared
      mvn -pl shared install
    command: |
      echo Copying settings
      cp -f /workspace/owlcms4/.gitpod/settings.xml /home/gitpod/.m2/settings.xml
      echo creating shared
      mvn -pl shared install

vscode:
  extensions:
    - redhat.fabric8-analytics


