
image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 8082
    onOpen: open-browser

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - name: init
    init: echo 'init script' # runs during prebuild
    
  - name: start
    command: echo 'start script'
    
  - name: copy
    command: cp /workspace/owlcms4/.gitpod/settings.xml /home/gitpod/.m2/settings2.xml

vscode:
  extensions:
    - redhat.fabric8-analytics