trigger:
  - none

parameters:
  - name: Revision
    type: string
    default: 4.7.5-rc02
  - name: BuildPublicResults
    type: string
    default: 'true'

# normally, no need to change anything below.
variables:
  - group: ReleaseRepoCredentials
  - template: src/main/azure-pipelines/variables-releaseRepoCredentials.yml
  - template: src/main/azure-pipelines/variables-common.yml

jobs:
  - template: src/main/azure-pipelines/job-top.yml