trigger:
  - develop

parameters:
  - name: Revision
    type: string
    default: 4.7.5-rc02
  - name: BuildPublicResults
    type: string
    default: 'true'

# normally, no need to change anything below.
variables:
  - name: Revision
    value: ${{ parameters.Revision }}
  - name: BuildPublicResults
    value: ${{ parameters.Revision }}
  - group: ReleaseRepoCredentials
  - template: variables-releaseRepoCredentials.yml
  - name: BuildGoal
    value: deploy # deploy | package (deploy sends to bintray)
  - name: MavenCacheFolder
    value: $(Pipeline.Workspace)/.m2/repository
  - name: MavenOpts
    value: -Dmaven.repo.local=$(MavenCacheFolder) -Drevision=$(Revision)

jobs:
  - template: src/main/azure-pipelines/job-top.yml