trigger:
  - develop

parameters:
  - name: Revision
    type: string
    default: 4.7.5-rc02
  - name: BuildPublicResults
    type: string
    default: 'true'

# normally, no need to change anything below.
variables:
  - group: ReleaseRepoCredentials
  - template: src/main/azure-pipelines/variables-releaseRepoCredentials.yml
  # - template: src/main/azure-pipelines/variables-common.yml
  # -Drevision overrides .mvn config; must be unique if BuildGoal is set to deploy.
  - name: Revision
    value: ${{ parameters.Revision }}
  # if BuildGoal = 'deploy', the uberjars will be published on bintray.  'package' does not deploy
  # to bintray, so Revision can be kept for several runs when debugging the installers.
  - name: BuildGoal
    value: deploy
  - name: MavenCacheFolder
    value: $(Pipeline.Workspace)/.m2/repository
  - name: MavenOpts
    value: -Dmaven.repo.local=$(MavenCacheFolder) -Drevision=$(Revision)

jobs:
  - template: src/main/azure-pipelines/job-top.yml