kind: Service
apiVersion: v1
metadata:
  name: owlcms-frontend
spec:
  selector:
    app: owlcms-frontend
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owlcms-frontend
spec:
  selector:
      matchLabels:
        app: owlcms-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: owlcms-frontend
    spec:
      containers:
        - name: owlcms-frontend
          image: owlcms:${dockerTag}
          imagePullPolicy: Never
          ports:
            - containerPort: 8080