kind: Secret
apiVersion: v1
metadata:
  name: publicresults-config
  labels:
    app: owlcms
stringData:
  OWLCMS_REMOTE: "http://publicresults-8080:8080"
  OWLCMS_UPDATEKEY: "kubernetes_internal"
type: Opaque