apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
  - name: owlcms-docker-containers.bintray.io/owlcms
    newTag: ${project.version}
  - name: owlcms-docker-containers.bintray.io/publicresults
    newTag: ${project.version}
resources:
- networkpolicies.yaml
- ingress.yaml
- services.yaml
commonLabels:
  environment: production
