apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

images:
- name: ${env.DOCKER_REG}/owlcms
  newTag: ${env.DOCKER_TAG}
- name: ${env.DOCKER_REG}/publicresults
  newTag: ${env.DOCKER_TAG}

resources:
- config.yaml
- clusterissuer.yaml
- nginx-service.yaml



