apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
  - name: owlcms-docker-containers.bintray.io/owlcms
    newTag: 4.9.2-rc01
  - name: owlcms-docker-containers.bintray.io/owlcms
    newTag: 4.9.2-rc01  
resources:
- networkpolicies.yaml
- ingress.yaml
- services.yaml
commonLabels:
  environment: production
  
  
