kind: Secret
apiVersion: v1
metadata:
  name: postgres-config
  labels:
    app: postgres
stringData:
  POSTGRES_DB: "owlcms_db"
  POSTGRES_USER: "owlcms"
  POSTGRES_PASSWORD: "owlcms"
  POSTGRES_HOST: "postgres"
type: Opaque
