apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: owlcms-ingress
spec:
  rules:
    - host: o.local
      http:
        paths:
          - backend:
              serviceName: owlcms-8080
              servicePort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: publicresults-ingress
spec:
  rules:
    - host: r.local
      http:
        paths:
          - backend:
              serviceName: publicresults-8080
              servicePort: 8080
