parameters:
  - name: jobName
    type: string
    default: ''
  - name: moduleName
    type: string
    default: ''
  - name: artifactName
    type: string
    default: ''
  - name: skipTests
    type: string
    default: 'false'

jobs:
  # build owlcms uberjar and zip to be used by installer
  - job: ${{ parameters.jobName }}
    pool:
      vmImage: ubuntu-latest
    container: gitpod/workspace-full:latest
    variables:
      - name: JAVA_HOME_11_X64
        value: /home/gitpod/.sdkman/candidates/java/11.0.15.fx-zulu
    steps:
      - template: steps-prepare-maven.yml
      - task: Maven@3.205.1
        displayName: build ${{ parameters.moduleName }} uberJar and publish to maven repository
        inputs:
          mavenPomFile: pom.xml
          mavenOptions: -Xmx3072m $(MavenOpts)
          javaHomeSelection: 'path'
          jdkDirectory: '/usr/local/openjdk-11'
          publishJUnitResults: true
          testResultsFiles: "**/surefire-reports/TEST-*.xml"
          effectivePomSkip: true
          goals: -P production -pl ${{ parameters.moduleName }} -am $(MavenOpts) -Dmaven.test.skip=${{ parameters.skipTests }} $(BuildGoal)
      - publish: $(Agent.BuildDirectory)/s/${{ parameters.moduleName }}/target/${{ parameters.moduleName }}.zip
        artifact: ${{ parameters.artifactName }}
