steps:
-  checkout: self
   submodules: recursive
-  task: MavenAuthenticate@0
   displayName: Populate settings.xml servers
   inputs:
      mavenServiceConnections: bintray-owlcms-maven
-  task: Cache@2
   displayName: Cache Maven local repository
   inputs:
      key: '"maven14.3.2d" | $(Agent.OS)'
      path: $(MavenCacheFolder)
- task: Maven@3
  displayName: update revision property
  inputs:
    mavenPomFile: pom.xml
    mavenOptions: -Xmx3072m $(MavenOpts)
    javaHomeOption: JDKVersion
    jdkVersionOption: "1.11"
    jdkArchitectureOption: x64
    publishJUnitResults: false
    goals: -N $(MavenOpts) -Dmaven.test.skip=true-Dproperty=revision -DnewVersion=$(Revision) versions:set-property 