steps:
-  checkout: self
   submodules: recursive
-  script: |
     echo A
     curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
     sudo apt-get install nodejs npm
-  script: |
     mkdir $HOME/.m2
     cp src/main/azure-pipelines/settings.xml $HOME/.m2/settings.xml
-  task: MavenAuthenticate@0
   displayName: Populate settings.xml for deploy servers
   inputs:
      mavenServiceConnections: owlcms-maven-repo
-  task: Cache@2
   displayName: Cache Maven local repository
   inputs:
      key: '"maven15.0.1a" | $(Agent.OS)'
      path: $(MavenCacheFolder)
- task: Maven@3.205.1
  displayName: update revision property
  inputs:
    mavenPomFile: pom.xml
    mavenOptions: -Xmx3072m $(MavenOpts)
    javaHomeOption: JDKVersion
    jdkVersionOption: "1.11"
    jdkArchitectureOption: x64
    publishJUnitResults: false
    goals: -N $(MavenOpts) -Dmaven.test.skip=true -Dproperty=revision -DnewVersion=$(Revision) versions:set-property 