apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
  - name: owlcms-docker-containers.bintray.io/owlcms
    newTag: 4.10.0-alpha01
  - name: owlcms-docker-containers.bintray.io/publicresults
    newTag: 4.10.0-alpha01
resources:
- ingress.yaml
- services.yaml
commonLabels:
  environment: production
