apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: owlcms
  name: owlcms-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
    - host: o.localhost
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: owlcms-8080
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: publicresults
  name: publicresults-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
    - host: r.localhost
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: publicresults-8080
                port:
                  number: 8080
