apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
- name: ${owlcms-docker}/owlcms
  newTag: "{{OWLCMS_VERSION}}"
- name: ${owlcms-docker}/publicresults 
  newTag: "{{PUBLICRESULTS_VERSION}}"
  
resources:
- ingress.yaml
- secrets.yaml
