kind: Secret
apiVersion: v1
metadata:
  name: owlcms-config
  labels:
    app: owlcms
stringData:
  OWLCMS_INITIALDATA: "LARGEGROUP_DEMO"
  OWLCMS_IP: ""
  OWLCMS_PIN: ""
  OWLCMS_RESETMODE: "false"
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: publicresults-config
  labels:
    app: publicresults
stringData:
  OWLCMS_LOCALE: "en_US"
  OWLCMS_REMOTE: "http://publicresults-8080:8080"
  OWLCMS_UPDATEKEY: "kubernetes_internal"
type: Opaque
---